apiVersion: apps/v1
kind: Deployment 
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: book-catalog
        image: sit722gayani.azurecr.io/book_catalog:3
        ports:
        - containerPort: 8000 
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722gayani_user:0boQVro1U44FZeqBcBxTp7aQYtEzFxQ9@dpg-crps5356l47c73aolt2g-a.oregon-postgres.render.com/sit722gayani"
          
---
apiVersion: v1
kind: Service 
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000


---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: inventory-management
        image: sit722gayani.azurecr.io/inventory_management:3
        ports:
        - containerPort: 8000 
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722gayani_user:0boQVro1U44FZeqBcBxTp7aQYtEzFxQ9@dpg-crps5356l47c73aolt2g-a.oregon-postgres.render.com/sit722gayani"
          
---
apiVersion: v1
kind: Service 
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  